# Site
repository: abhi2020-ds/abhi2020-ds.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abhineet Singh
title: Senior Advanced Analytics Engineer
email: abhi2020-ds@outlook.com
website: https://abhi2020-ds.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: 
github_username:  abhi2020-ds
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: abhineetsingh03
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: 
#  icon: 
#  url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Accomplished and results-driven Analytics Leader with over <mark>13</mark> years of progressive experience in data analytics and business intelligence. 
  Proven track record of engineering sophisticated data analytics solutions to drive business insights, enhance operational efficiency, and optimize decision-making processes. 
  A strategic thinker with a deep understanding of industry-specific data challenges, dedicated to driving organizational success through innovative data-driven strategies and effective team leadership.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Domino’s
        link: https://biz.dominos.com/
        link_text: dominos.com
        sub_title: Lead Data Analytics Engineer
        caption: June 2021 - Present
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            ● Engineered predictive analytics models using machine learning algorithms at Domino’s, boosting loyalty program’s forecast accuracy by 20%. \n
            ● Activated cross-functional teams, driving a 12% increase in customer growth and a 7% boost in orders and sales. \n
            ● Spearheaded strategic alignment of reporting KPIs, ensuring optimal business outcomes. \n
            ● Achieved outstanding 50% cut in data-ingestion runtime, accelerating time-to-insights. \n
            ● Increased dashboard user base by 48%, facilitating seamless data communication and insights consumption. \n
            ● Partnered with Senior Directors and Marketing VPs to establish key performance indicators (KPIs) for Marketing and Consumer Analytics Dashboards \n
            ● Engineered a Customer Retention Analytics Tracking Tool, bolstering retention strategies and targeted offer effectiveness. \n
            ● Streamlined data pipelines, ensuring robust integrity across platforms. \n
            ● Mentored team for a culture of continuous learning and high performance. \n
            ● Contributed to Azure Cloud Migration roadmap planning, enhancing operational efficiency. \n
            ● Demonstrated commitment to growth with Microsoft Certifications in Azure Data, Azure AI, and Power BI. \n
            ● Built A/B Testing Dashboard that helped data preparation process automated for analyzing marketing campaigns and customer take rates, ordering frequency changes.
      - layout: left
        title: Ally Financial
        link: https://www.ally.com/
        link_text: ally.com
        sub_title: Senior Data Analytics Engineer
        caption: October 2013 - May 2021
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            ● Led a team to optimize auto finance loan application processes using advanced analytics, reducing operations overhead by 30%. |
            ● Developed reporting products enabling Account Executives to track loan application seamlessly. Automated financial data models and complex dashboards, significantly reducing processing time. |
            ● Analyzed transactional data to uncover measurable insights in customer portfolio management and risk assessment. |
            ● Managed enterprise-scale analytics technology upgrades, ensuring seamless migration and platform integration.
      - layout: left
        title: TTI Of USA
        link: https://ttiofusa.com/
        link_text: ttiofusa.com
        sub_title: Senior Solutions Architect
        caption: August 2012 - Septermber 2013
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            ● Led a project team in upgrading enterprise reporting software, enhancing features and functionality for internal stakeholders. |
            ● Created an XML Parser tool, reducing data lineage documentation upkeep by 40%. |
            ● Delivered business reports for Sales and Account Executive Leadership. |
            ● Developed cross-integration solutions to improve data governance and ensure consistency across reporting systems.
      - layout: left
        title: Reliable Software Resources
        link: https://www.rsrit.com/
        link_text: rsrit.com
        sub_title: Data Analytics Consultant
        caption: March 2011 - July 2012
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            ● Created Dimensional Models and Cubes using Cognos Reporting suites. |
            ● Engineered intricate ETL pipelines with Informatica, decreasing deployment time through automated scripting. |
            ● Partnered with data architects and stakeholder committee members to offer insights on six-sigma model-based supply chain reporting. |
            ● Improved incident support ticket SLAs for reporting platforms.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Of Illinois at Springfield
        caption: 2009 - 2010
        sub_title: M.S Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
