# Site
repository: abhi2020-ds/abhi2020-ds.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abhineet Singh
title: Senior Advanced Analytics Engineer
email: abhi2020-ds@outlook.com
website: https://devgyan.work/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: 
github_username:  abhi2020-ds
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: abhineetsingh03
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: 
#  icon: 
#  url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Seasoned Data Science and Analytics aficionado with over 13 years of experience in transforming data into actionable insights. 
 My journey has taken me through the realms of finance, manufacturing, and quick-service restaurants (QSR), where I've honed my skills in predictive modeling, advanced analytics, and data-driven decision-making that significantly boost business performance. 
 I thrive on solving complex data challenges and creating innovative solutions that drive business growth. Whether it's designing intuitive dashboards, automating data pipelines, or ensuring data integrity across platforms. 
 I love turning raw data into strategic gold. Known for strategic vision, meticulous attention to detail, and the ability to translate complex data insights into clear, compelling narratives for senior leadership.
 Dedicated to fostering a culture of continuous learning and professional development within high-performing teams.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Domino’s
        link: https://biz.dominos.com/
        link_text: dominos.com
        sub_title: Lead Data Analytics Engineer
        caption: June 2021 - Present
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            - Engineered predictive analytics models using machine learning algorithms at Domino’s, boosting loyalty program’s forecast accuracy by 20%. 
            - Activated cross-functional teams, driving a 12% increase in customer growth and a 7% boost in orders and sales.
            - Spearheaded strategic alignment of reporting KPIs, ensuring optimal business outcomes.
            - Achieved outstanding 50% cut in data-ingestion runtime, accelerating time-to-insights.
            - Increased dashboard user base by 48%, facilitating seamless data communication and insights consumption.
            - Partnered with Senior Directors and Marketing VPs to establish key performance indicators (KPIs) for Marketing and Consumer Analytics Dashboards.
            - Engineered a Customer Retention Analytics Tracking Tool, bolstering retention strategies and targeted offer effectiveness.
            - Streamlined data pipelines, ensuring robust integrity across platforms.
            - Mentored team for a culture of continuous learning and high performance.
            - Contributed to Azure Cloud Migration roadmap planning, enhancing operational efficiency.
            - Demonstrated commitment to growth with Microsoft Certifications in Azure Data, Azure AI, and Power BI.
            - Built A/B Testing Dashboard that helped data preparation process automated for analyzing marketing campaigns and customer take rates, ordering frequency changes.
      - layout: left
        title: Ally Financial
        link: https://www.ally.com/
        link_text: ally.com
        sub_title: Senior Data Analytics Engineer
        caption: October 2013 - May 2021
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            - Led a team to optimize auto finance loan application processes using advanced analytics, reducing operations overhead by 30%.
            - Developed reporting products enabling Account Executives to track loan application seamlessly. Automated financial data models and complex dashboards, significantly reducing processing time.
            - Analyzed transactional data to uncover measurable insights in customer portfolio management and risk assessment.
            - Managed enterprise-scale analytics technology upgrades, ensuring seamless migration and platform integration.
      - layout: left
        title: TTI Of USA
        link: https://ttiofusa.com/
        link_text: ttiofusa.com
        sub_title: Senior Solutions Architect
        caption: August 2012 - Septermber 2013
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            - Led a project team in upgrading enterprise reporting software, enhancing features and functionality for internal stakeholders.
            - Created an XML Parser tool, reducing data lineage documentation upkeep by 40%.
            - Delivered business reports for Sales and Account Executive Leadership.
            - Developed cross-integration solutions to improve data governance and ensure consistency across reporting systems.
      - layout: left
        title: Reliable Software Resources
        link: https://www.rsrit.com/
        link_text: rsrit.com
        sub_title: Data Analytics Consultant
        caption: March 2011 - July 2012
        quote: >
          Solving business problems by designing game changing data analytics products.
        description: | # this will include new lines to allow paragraphs
            - Created Dimensional Models and Cubes using Cognos Reporting suites.
            - Engineered intricate ETL pipelines with Informatica, decreasing deployment time through automated scripting.
            - Partnered with data architects and stakeholder committee members to offer insights on six-sigma model-based supply chain reporting.
            - Improved incident support ticket SLAs for reporting platforms.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Of Illinois at Springfield
        caption: 2009 - 2010
        sub_title: M.S Computer Science
        quote: >
         University was established by the Illinois General Assembly in 1969 as Sangamon State University with a focus on post-graduate education. It became the third member of the University of Illinois system on July 1, 1995. No. 1 public regional university in Illinois (2020, 2021, 2022, 2023, 2024).
        description: | # this will include new lines to allow paragraphs
          During my time at UIS I learnt most of my key skills that I have taken through my career such as teamwork and working to strict deadlines. I thouroughly enjoyed my time in university and learnt a lot about a healthy work life balance.
          I spent my extra time as a committee member of the *Indian Student Organization* taking on roles such as *President* and *Vice-President*.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Customer Rating Analysis
        link: https://devgyan.work/blog/csa/
        link_text: Customer Rating Dashboard - Yelp & Zomato
        additional_links:
          - title:  Restaurant Rating Analysis - Yelp & Zomato
            icon: fab fa-github
            url: https://devgyan.work/blog/csa/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Gathering customer ratings on local restaurants and providing insights around several business KPIs using R Flexboard through Yelp and Zomato API calls.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way for learning <mark>R and Python</mark>. I have learned many skills through this and been I'm very proud of having this in my portfolio.
      - layout: top-middle
        title: Beautiful Soup Of Sport
        link: https://devgyan.work/blog/webscrp/
        link_text: Beautiful Soup Of Sport
        additional_links:
          - title:  Beautiful Soup Of Sport
            icon: fab fa-github
            url: https://devgyan.work/blog/webscrp/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Web scraping program to look into ATP stats for legends of tennis sports Roger Federer, Rafa Nadal and Novak Djockovic.
        description: | # this will include new lines to allow paragraphs
          I started this project to leverage <mark>Python</mark> and generate a time series visual for showcasing the grand slam race. This is a cool visual generating year over year race between 3 sports icon.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data engineering, analytics and science some of my other interests and hobbies are:
      - Tech Innovation
      - Blogging
      - Tennis
      - Music

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
